### ISSUE TITLE
mkl module file location doesn't agree with roll-test

### ISSUE THREAD

**Issue by tcooper** [sdsc/intel-roll#2]
Compare the `mkl-modules/Makefile` [location](https://github.com/sdsc/intel-roll/blob/master/src/mkl-modules/Makefile#L59) for the mkl module file with the [location](https://github.com/sdsc/intel-roll/blob/master/src/roll-test/intel.t#L210) examined in the `roll-test/intel.t`

One of them is wrong... which one should we change @jerrypgreenberg / @jjhayes ?

**Comment by jjhayes** [comment]
Resolved by commit 731ebd9a595fa312bc75fa23e956e1914a2e22ab.
