### ISSUE TITLE
Environment variable FPATH confliction with zsh

### ISSUE THREAD

**Issue by qobilidop** [sdsc/intel-roll#4]
I was trying to use zsh on TSCC. I installed it through Linuxbrew in my home directory. But then I see the `function definition file not found` errors all over my screen. zsh uses the environment variable `FPATH` to locate function definition files, but somehow it's been overwritten. Eventually my investigation leads me to the intel module, where the `FPATH` environment variable is set, which overwrites the zsh settings. And loading the intel module happens in `/etc/zshrc` which I cannot modify.

The solutions I could think of now are the following:

- Do not use zsh on TSCC.
- Appending to instead of setting `FPATH`.
- Reset `FPATH` in ~/.zshrc manually. (What I'm doing now)

I'd like to know the expert's suggestions and possibly more elegant solutions.

Thanks!

**Comment by jjhayes** [comment]
Hi Bili,

I looked into this, and it's an interesting issue. The Intel MKL compilation process uses the FPATH environment variable--presumably to locate the Fortran header files--along with CPATH and INCLUDE. The collision wouldn't normally cause a problem unless you were trying to compile with MKL while running zsh; however, the fact that the Intel module is loaded by default on the SDSC clusters means that, as you noted, /etc/zshrc pulls in the setting. I think that your solution of resetting FPATH in ~/.zshrc is probably the best available.

Jim

**Comment by qobilidop** [comment]
Hi Jim,

Thanks for your comments! I'm happy with my current solution and there's no further request.

Bili
